Repository GarudaHacks/gh-portal, pull requests merged in 2025-05, with the labels that each got.

#15 Feat/user and application
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/components/ApplicationInquiry.tsx
  src/components/ApplicationProfile.tsx
  src/components/Auth.tsx
  src/components/AuthLoginComponent.tsx
  src/components/AuthRegisterComponent.tsx
  src/components/Sidebar.tsx
  src/components/ui/calendar.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/popover.tsx
  src/context/AuthContext.d.ts
  src/context/AuthContext.jsx
  src/context/AuthContext.tsx
  src/lib/application-utils.tsx
  src/main.tsx
  src/model/User.ts
  src/pages/Application.tsx
  src/pages/Home.tsx
  src/types/application.ts
  src/utils/applicationUtils.ts
  src/utils/firebase.ts
  tsconfig.app.json
  vite.config.ts
Labels: Review effort 4/5

#20 Fix/faq and logs
  package-lock.json
  package.json
  src/components/ApplicationAdditionalQuestion.tsx
  src/components/ApplicationInquiry.tsx
  src/components/ApplicationProfile.tsx
  src/components/EventSchedule.tsx
  src/components/Sidebar.tsx
  src/components/SidebarTab.tsx
  src/components/ui/accordion.tsx
  src/context/AuthContext.tsx
  src/data/faq.ts
  src/data/questions.ts
  src/data/sampleEvents.ts
  src/lib/application-utils.tsx
  src/model/User.ts
  src/pages/Faq.tsx
  src/types/application.ts
  src/types/applicationStatus.ts
Labels: Review effort 4/5

#25 Merge from Dev
  components.json
  index.html
  jest.config.js
  src/assets/data/copywriting.ts
  src/components/ApplicationInquiry.tsx
  src/components/ApplicationIntro.tsx
  src/components/Auth.tsx
  src/components/AuthLoginComponent.tsx
  src/components/DayIndicator.tsx
  src/components/EventCard.tsx
  src/components/EventTypeLegend.tsx
  src/components/Page.tsx
  src/components/PageHeader.tsx
  src/components/QuestionForm.tsx
  src/components/Ticket.tsx
  src/components/TimelineHeader.tsx
  src/components/ui/accordion.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/context/AuthContext.tsx
  src/data/faq.ts
  src/data/questions.ts
  src/data/sampleEvents.ts
  src/index.css
  src/main.tsx
  src/model/User.ts
  src/pages/Faq.tsx
  src/pages/Home.tsx
  src/pages/Mentorship.tsx
  src/pages/Schedule.tsx
  src/pages/Ticketing.tsx
  src/types/application.ts
  src/types/applicationStatus.ts
  src/types/eventTypes.ts
  src/utils/applicationUtils.ts
  src/utils/eventUtils.ts
  src/utils/firebase.ts
  tailwind.config.js
  tsconfig.app.json
  vercel.json
Labels: Review effort 3/5

#26 Fix/additional questions
  README.md
  package-lock.json
  package.json
  src/assets/data/copywriting.ts
  src/components/Datepicker.tsx
  src/components/ui/button.tsx
  src/context/AuthContext.tsx
  src/lib/application-utils.tsx
  src/main.tsx
  src/pages/Application.tsx
  src/pages/Home.tsx
  tsconfig.json
Labels: Review effort 4/5

#30 required field asterisk
  src/lib/application-utils.tsx
Labels: Review effort 2/5

#31 fix homepage application status; improve home ui
  src/pages/Home.tsx
  src/utils/homeUtils.ts
Labels: Review effort 3/5

#32 feat: email verification
  src/components/Auth.tsx
  src/components/AuthLoginComponent.tsx
  src/components/AuthRegisterComponent.tsx
  src/components/AuthVerificationComponent.tsx
  src/context/AuthContext.tsx
Labels: Review effort 4/5

#36 add looking for teammates q
  src/data/questions.ts
  src/pages/Application.tsx
Labels: Review effort 2/5
