Repository GarudaHacks/gh-portal, pull requests merged in 2025-03, with the labels that each got.

#6 Feat/route dashboard
  public/images/icons/arrow_outward.svg
  public/images/icons/arrow_outward_altcolor.svg
  public/images/icons/calendar_month.svg
  public/images/icons/confirmation_number.svg
  public/images/icons/contact_support.svg
  public/images/icons/cottage.svg
  public/images/icons/group_search.svg
  public/images/icons/more_vert.svg
  src/App.tsx
  src/Home.tsx
  src/components/Sidebar.tsx
  src/pages/Faq.tsx
  src/pages/Home.tsx
  src/pages/Mentorship.tsx
  src/pages/Schedule.tsx
  src/pages/Ticket.tsx
Labels: Review effort 4/5

#8 Feat/route dashboard: Code Refactor & Removed unused import
  src/components/PageHeader.tsx
  src/components/Sidebar.tsx
  src/components/SidebarLink.tsx
  src/pages/Faq.tsx
  src/pages/Home.tsx
  src/pages/Mentorship.tsx
  src/pages/Schedule.tsx
  src/pages/Ticket.tsx
Labels: Review effort 3/5

#10 Feat/portal 02 hacker application page
  components.json
  package-lock.json
  package.json
  public/images/icons/arrow_back_ios.svg
  public/images/icons/arrow_backward.svg
  public/images/icons/arrow_forward.svg
  public/images/icons/sign_out.svg
  public/images/icons/sign_out_white.svg
  public/images/logo/gh_logo-color.png
  src/App.tsx
  src/assets/data/copywriting.ts
  src/components/ApplicationAdditionalQuestion.tsx
  src/components/ApplicationInquiry.tsx
  src/components/ApplicationIntro.tsx
  src/components/ApplicationNavbar.tsx
  src/components/ApplicationProfile.tsx
  src/components/ApplicationSubmitted.tsx
  src/components/Auth.tsx
  src/components/HomeStatusNotRsvpd.tsx
  src/components/RedGradientBackground.tsx
  src/components/Sidebar.tsx
  src/components/ui/button.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/select.tsx
  src/components/ui/textarea.tsx
  src/context/AuthContext.d.ts
  src/index.css
  src/lib/application-utils.tsx
  src/lib/utils.ts
  src/pages/Application.tsx
  src/pages/Home.tsx
  src/types/application.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: bug, enhancement, Review effort 5/5

#11 feat: firebase emulators
  .firebaserc
  .gitignore
  firebase.json
  firestore.indexes.json
  firestore.rules
  src/utils/firebase.ts
  storage.rules
Labels: Review effort 3/5
